{{- $fullName := include "outline-artifact.fullname" . -}}
{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
  labels:
  {{- include "outline-artifact.labels" . | nindent 4 }}
  {{- with .Values.istio.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gateways:
    - {{ $fullName }}
  hosts:
  {{- $hostDict := dict }}
  {{- range .Values.istio.servers }}
    {{- range $element := .hosts }}
      {{- if eq (hasKey $hostDict $element) false }}
      {{- $_ := set $hostDict $element $element }}
        - "{{ . }}"
      {{- end }}
    {{- end }}
  {{- end }}
  http:
  {{- range .Values.istio.servers }}
    - match:
      - uri:
          prefix: {{ .path }}
    {{- if .retries }}
      retries:
        {{- toYaml .retries | nindent 8 }}
    {{- end }}
      route:
        - destination:
            host: {{ .virtualserviceHost | default $fullName | quote }}
            port:
              number: {{ .port.number }}
      {{- if .corsPolicy }}
      corsPolicy:
        {{- toYaml .corsPolicy | nindent 8 }}
      {{- end }}
      {{- if .headers }}
      headers:
        {{- toYaml .headers | nindent 8 }}
      {{- end }}
  {{- end }}
{{- end }}
